### ISSUE TITLE
RangeError when trying to pair device

### ISSUE THREAD

**Issue by tfischer4765** [as19git67/simnuki#4]
I get a range error when trying to pair my Huawei P10 with the simulated device. Note please that I've implemented the android fix proposed in #3. I can't verify if that causes the problem because without the fix, the simulated nuki isn't detected at all.
Step 14: verifying authorization authenticator...
Step 14: authenticators verified ok
Step 15: creating one time challenge...
Step 15: sending one time challenge...
Step 15: sending one time challenge...
PairingGeneralDataInputOutputCharacteristic - onSubscribe
don't have more data to notify
PairingGeneralDataInputOutputCharacteristic - onUnsubscribe
buffer.js:934
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:934:11)
    at Buffer.readUInt16LE (buffer.js:980:5)
    at Gatt.onAclStreamEnd (/home/pi/simnuki/node_modules/bleno/lib/hci-socket/gatt.js:283:68)
    at emitNone (events.js:110:20)
    at AclStream.emit (events.js:207:7)
    at AclStream.push (/home/pi/simnuki/node_modules/bleno/lib/hci-socket/acl-stream.js:28:10)
    at BlenoBindings.onDisconnComplete (/home/pi/simnuki/node_modules/bleno/lib/hci-socket/bindings.js:161:21)
    at emitTwo (events.js:125:13)
    at Hci.emit (events.js:213:7)
    at Hci.onSocketData (/home/pi/simnuki/node_modules/bleno/lib/hci-socket/hci.js:410:12)

**Comment by filipnavara** [comment]
This is actually same issue as #2. I pasted a fix for it there.
